spring.application.name=auth-service
server.port=8085

# JWT Configuration
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Eureka Configuration
eureka.client.service-url.defaultZone=http://servicereg:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/doctorapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Zipkin Configuration
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

# Logging Configuration
logging.level.com.cs.authservice=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=INFO 