---
- name: Apply Kubernetes manifests via roles
  hosts: localhost
  remote_user: rohan-sonawane
  become: false
  roles:
    - database
    - pgadmin
    - redis
    - patient_service
    - doctor_service
    - appointment_service
    - gateway
    - monitoring
    - tracing
    - hpa

