---
# Gateway Microservice Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-ms
          image: imrds7/gateway-ms:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

---
# Gateway Microservice NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: gateway-ms
spec:
  type: NodePort
  selector:
    app: gateway-ms
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30085  # You can choose any port in 30000-32767
